### ISSUE TITLE
Audio clip

### ISSUE THREAD

**Issue by ClickHerexe** [petzku/Aegisub-Scripts#4]
When there are multiaudio (english-japanese) and I select japanese in aegisub, the script takes the first one (in that case english)

**Comment by petzku** [comment]
AFAIK, there's no easy way to tell which audio track is loaded from within the lua scripting interface. The best workaround I can offer is to manually select the second track by (temporarily) adding `--aid=2` (or `--alang=jpn`) into the "custom options" section in the configuration dialog.
